import { notFound, redirect } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { phDate } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { ChevronLeft } from "lucide-react";
import { PrintButton } from "@/components/print-button";

export default async function COEPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const session = await auth();
  if (!session) redirect("/login");

  const actor = await prisma.user.findUnique({ where: { email: session.user!.email! }, select: { companyId: true } });
  if (!actor?.companyId) redirect("/dashboard");

  const e = await prisma.employee.findFirst({
    where: { id, companyId: actor.companyId },
    include: { company: true },
  });
  if (!e) notFound();

  const co = e.company;
  const yearsOfService = (Date.now() - +e.dateHired) / (1000 * 60 * 60 * 24 * 365.25);
  const issuedDate = new Date();

  return (
    <div className="max-w-2xl mx-auto space-y-5">
      <div className="flex items-center justify-between print:hidden">
        <Link href={`/employees/${id}`} className="inline-flex items-center gap-1 text-xs text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors">
          <ChevronLeft className="h-3 w-3" /> Back to profile
        </Link>
        <PrintButton />
      </div>

      {/* COE Document */}
      <div id="payslip" className="rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--bg-elevated)] p-10 space-y-8 print:border-0">
        {/* Letterhead */}
        <div className="text-center space-y-1 pb-6 border-b border-[var(--border)]">
          <div className="h-10 w-10 rounded-[var(--radius-sm)] bg-[var(--brand)] flex items-center justify-center mx-auto mb-3">
            <span className="text-white font-bold text-lg">S</span>
          </div>
          <div className="text-lg font-bold">{co.name}</div>
          {co.address && <div className="text-sm text-[var(--text-secondary)]">{co.address}</div>}
          {co.tin && <div className="text-xs text-[var(--text-tertiary)]">TIN: {co.tin}</div>}
        </div>

        {/* Title */}
        <div className="text-center space-y-1">
          <div className="text-xl font-bold tracking-wide uppercase">Certificate of Employment</div>
          <div className="text-xs text-[var(--text-tertiary)] uppercase tracking-widest">To Whom It May Concern</div>
        </div>

        {/* Body */}
        <div className="space-y-5 text-sm leading-relaxed text-[var(--text-primary)]">
          <p>
            This is to certify that{" "}
            <strong>{e.firstName} {e.middleName ? e.middleName + " " : ""}{e.lastName}</strong>,
            with Employee No. <strong>{e.employeeNumber}</strong>, is/was a bonafide employee of{" "}
            <strong>{co.name}</strong>.
          </p>

          <table className="w-full text-sm border-collapse">
            <tbody>
              {[
                ["Position", e.position],
                ["Department", e.department],
                ["Employment Status", e.employmentStatus],
                ["Date Hired", phDate(e.dateHired)],
                ["Length of Service", `${yearsOfService.toFixed(1)} year${yearsOfService >= 2 ? "s" : ""}`],
                ["Basic Monthly Salary", `₱${e.basicMonthlyRate.toLocaleString("en-PH", { minimumFractionDigits: 2 })}`],
              ].map(([label, value]) => (
                <tr key={label} className="border-b border-[var(--border)] last:border-0">
                  <td className="py-2 pr-6 font-medium text-[var(--text-secondary)] w-48">{label}</td>
                  <td className="py-2">{value}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <p>
            This certification is issued upon the request of the above-named employee for
            whatever legal purpose it may serve.
          </p>
        </div>

        {/* Signature block */}
        <div className="pt-8 grid grid-cols-2 gap-12">
          <div className="space-y-12">
            <div>
              <div className="border-b border-[var(--text-primary)] w-48 mb-1" />
              <div className="text-xs font-medium">Authorized Signatory</div>
              <div className="text-xs text-[var(--text-tertiary)]">HR Manager / Owner</div>
              <div className="text-xs text-[var(--text-tertiary)]">{co.name}</div>
            </div>
          </div>
          <div className="text-right text-xs text-[var(--text-tertiary)] space-y-1">
            <div>Issued: {phDate(issuedDate)}</div>
            <div>Valid for 30 days from date of issue</div>
            {co.tin && <div>TIN: {co.tin}</div>}
          </div>
        </div>

        <div className="pt-4 border-t border-dashed border-[var(--border)] text-center">
          <p className="text-[10px] text-[var(--text-tertiary)]">
            This document is system-generated by MMTSI HRIS · {co.name} · {phDate(issuedDate)}
          </p>
        </div>
      </div>
    </div>
  );
}
